"""
Developer Agent Worker
Consumes from developer_queue, generates code and implementation
"""

import asyncio
import logging
import os
import uuid
from base_agent import BaseAgent, LLMClient
from typing import Dict

logger = logging.getLogger(__name__)

class DeveloperAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            agent_name='Developer',
            queue_name='developer_queue',
            next_queue='tester_queue'
        )

    async def generate_output(self, task_id: str, task_input: str, previous_outputs: Dict) -> dict:
        """Generate development output"""
        planner_output = previous_outputs.get('planner', {})
        researcher_output = previous_outputs.get('researcher', {})

        plan_text = planner_output.get('plan', 'No plan available')
        research_text = researcher_output.get('research', 'No research available')

        prompt = f"""You are a senior full-stack developer in a multi-agent AI system. Based on the task, plan, and research, create a complete implementation.

Task: {task_input}

Planner's Plan:
{plan_text}

Research Findings:
{research_text}

Your implementation should include:
1. Complete code structure and architecture
2. Key components and modules
3. API endpoints and data models
4. Database schema and migrations
5. Frontend components and UI structure
6. Configuration and environment setup
7. Deployment considerations
8. Code examples and patterns

Generate production-ready code with proper error handling, documentation, and best practices."""

        try:
            response = LLMClient.request(prompt, max_tokens=1500, temperature=0.3)

            # Generate project files
            project_id = str(uuid.uuid4())
            project_dir = f"generated_projects/{project_id}"
            os.makedirs(project_dir, exist_ok=True)

            # Create basic project structure
            await self.create_project_files(project_dir, response, task_input)

            return {
                'name': 'Developer',
                'role': 'Full-Stack Developer',
                'implementation': response,
                'project_id': project_id,
                'project_dir': project_dir,
                'timestamp': str(asyncio.get_event_loop().time())
            }
        except Exception as e:
            logger.error(f"Developer LLM request failed: {e}")
            return {
                'name': 'Developer',
                'role': 'Full-Stack Developer',
                'implementation': f"Error generating implementation: {str(e)}",
                'timestamp': str(asyncio.get_event_loop().time())
            }

    async def create_project_files(self, project_dir: str, implementation: str, task_input: str):
        """Create project files based on implementation"""
        try:
            # Create README
            readme_content = f"""# Generated Project

Task: {task_input}

## Implementation Overview

{implementation[:500]}...

## Getting Started

1. Install dependencies
2. Configure environment
3. Run the application

## Project Structure

- This project was generated by the Developer Agent
- Contains complete implementation based on planning and research phases
"""

            with open(f"{project_dir}/README.md", 'w') as f:
                f.write(readme_content)

            # Create package.json for Node.js projects
            package_json = {
                "name": f"generated-project-{os.path.basename(project_dir)}",
                "version": "1.0.0",
                "description": f"Generated project for: {task_input[:50]}...",
                "main": "index.js",
                "scripts": {
                    "start": "node index.js",
                    "dev": "nodemon index.js",
                    "test": "jest"
                },
                "keywords": ["generated", "ai", "agentflow"],
                "author": "AgentFlow AI",
                "license": "MIT"
            }

            import json as json_lib
            with open(f"{project_dir}/package.json", 'w') as f:
                json_lib.dump(package_json, f, indent=2)

            # Create basic index.js
            index_js = """// Generated by AgentFlow Developer Agent
console.log('Project generated successfully!');
console.log('Check README.md for implementation details');

// TODO: Implement based on the generated specification
"""

            with open(f"{project_dir}/index.js", 'w') as f:
                f.write(index_js)

            logger.info(f"Created project files in {project_dir}")

        except Exception as e:
            logger.error(f"Failed to create project files: {e}")

async def main():
    """Main entry point for Developer agent"""
    agent = DeveloperAgent()
    try:
        await agent.start_consuming()
    except KeyboardInterrupt:
        await agent.shutdown()

if __name__ == "__main__":
    asyncio.run(main())